---
title: "Historical Water Level Report"
author: "Paula"
date: "`r Sys.Date()`"
output: html_document
params: 
  stations: 
    - "08MF005"
    - "08NM174"
  YOI: 2024
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rmarkdown)
library(dplyr)
library(ggplot2)
library(lubridate)
library(tidyhydat)
library(hydroGraphR)
library(flextable)
library(kableExtra)
library(purrr)
library(formattable)
library(data.table)
library(htmltools)
library(knitr)


source("R/getQ.R")

```

## Example data: Replace this with actual data loading code

```{r read data, include=FALSE}

stations <- params$stations

# Accessing the YOI parameter
YOI <- params$YOI

message("Downloading hydro data...")
all_stations_data <- hydroGraphR::dl_hydro(stations)

uniq_stns <- all_stations_data %>% 
  distinct(STATION_NUMBER) 

uniq_stns <- uniq_stns$STATION_NUMBER


```


### Example data: Replace this with actual data loading code


```{r stations data, include = FALSE,  results='asis'}

# gradient_color -----------------------------------

format_color <- function(x) {
  ifelse(x < 90, formattable::color_tile("red", "#FFFFEE")(x), color_tile("#EEFFEF", "darkgreen")(x))
}

# ---------------------------------------------------

```

```{r, echo=FALSE, results='asis'}
walk(uniq_stns, function(st){
  st_df <- all_stations_data %>% 
    filter(STATION_NUMBER %in% st)
  
  stats_table <- create_stats_table(st_df, YOI = YOI)

  stats_table$perc_hist <- formattable::formattable(stats_table$perc_hist, formatter = format_color)


  kbl(stats_table, "html", booktabs = TRUE, escape = FALSE) %>% 
    print()
  cat('\n\n<!-- -->\n\n')
})
```









