---
title: "hydro_weekly_summary"
author: "psoto"
date: "2024-05-24"
output: html_document

---

```{r setup, include=FALSE}

# REPRODUCABLE WORKING KABLE PLOT


library(tidyverse)
library(tidyhydat)
library(DT)
library(kableExtra)
library(formattable)

BC_stations <- hy_stations(prov_terr_state_loc = "BC") %>%
  filter(HYD_STATUS == "ACTIVE")


summarize_weekly_flow <- function(station_number, date = Sys.Date()){
  
  print(station_number)
  print("start script")
  
  historical <- hy_daily(station_number =  station_number)
  realtime <- realtime_dd(station_number = station_number)
  
  
  # select week ------------------------
  print("select week")
  today <- date
  sprintf("Date: %s", today)
  
  day_of_week <- wday(today) 
  sprintf("Day of Week: %s", day_of_week)
  
  
  # Calculate the last Saturday
  last_saturday <- today - day_of_week
  
  # Calculate the previous Sunday (end of the last full week)
  last_sunday <- last_saturday - 6
  
  #--------------------------------------
  print("filter historical and real time data")
  
  # Filter the data frame for the last full week
  last_full_week_data <- realtime %>%
    filter(Date >= last_sunday & Date <= last_saturday) 
  
  last_full_week_data_mean <- last_full_week_data %>%
    group_by(Date = date(Date)) %>%
    summarise(current_week_mean_flow = mean(Value)) %>%
    mutate(month_day = substr(Date, 6,12))
  
  dates_of_interest <- last_full_week_data_mean$month_day
  
  last_sunday_month <- month(last_sunday)
  last_sunday_day <- day(last_sunday)
  last_saturday_month <- month(last_saturday)
  last_saturday_day <- day(last_saturday)
  
  historical_dates <- historical %>%
    mutate(month_day = substr(Date, 6,12), 
           year = year(Date)) 
  
  print("Summarize data")
  
  
  historical_dates <- historical_dates %>%
    filter(month_day %in% dates_of_interest) 
  
  historical_week_averaged <- historical_dates %>%
    group_by(year) %>%
    summarise(historical_mean_flow = mean(Value))

  week_of_interest_stats <-  historical_week_averaged %>%
    summarise(q25 = quantile(historical_mean_flow, 0.25, na.rm = TRUE),
              q75 = quantile(historical_mean_flow, 0.75, na.rm = TRUE),
              historical_mean = mean(historical_mean_flow, 0.25, na.rm = TRUE))
    
  
  week_of_interest_mean <- mean(last_full_week_data_mean$current_week_mean_flow, na.rm = TRUE)
  
  perc_of_normal <- (week_of_interest_stats$historical_mean/mean(historical_week_averaged$historical_mean_flow, na.rm = TRUE))*100
  
  
  
  week_of_interest_stats_all <- week_of_interest_stats %>%
    mutate(station_number = station_number, .before = "q25",
           week_of_interest_mean = week_of_interest_mean,
           perc_of_normal = perc_of_normal)
  

  return(week_of_interest_stats_all)
  
}


flow_table <- bind_rows(map(c("09AA004", "09AA017", "09AB004", "09AB001", "09AE002", 
                              "09AH004", "09DC006", "09EA003", "10AA001"), summarize_weekly_flow))
flow_table <- as.data.frame(flow_table)
```



```{r print data table, echo=FALSE}
format_color <- function(x) {
  ifelse(x < 90, formattable::color_tile("red", "#FFFFEE")(x), color_tile("#EEFFEF", "darkgreen")(x))
}

# Apply formatting to the percent_of_normal_discharge column
flow_table$perc_of_normal <- formattable::formattable(flow_table$perc_of_normal, formatter = format_color)

# Create the table
kbl(flow_table, "html", booktabs = TRUE, escape = FALSE) 

```



